query GetContasMtAuth {
  GetContasMtAuth {
    contas {
      id
      conta
      work
      investAtual
      investAberturaInit
      serverMetaTrader
      attributesMeta
      password
    }
    error
  }
}
